server:
  port: 2001

spring:
  application:
    name: seata-order-server

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.116.129:3306/test_seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.116.129:8848
        namespace: 45d76f2d-471c-4570-90df-fc1c467a983a
        group: SEATA_GROUP

seata:
  tx-service-group: test_tx_group
  service:
    vgroup-mapping:
      test_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: http://192.168.116.129:8848
      namespace: 45d76f2d-471c-4570-90df-fc1c467a983a
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: http://192.168.116.129:8848
      namespace: 45d76f2d-471c-4570-90df-fc1c467a983a
      group: SEATA_GROUP
      data-id: seataServer.properties

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.crz.springcloud.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: info
