server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.116.129:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'