server:
  port: 2003

spring:
  application:
    name: seata-account-server

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.116.129:3306/test_seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.116.129:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    io:
      seata: info
