server:
  port: 1000

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order80_route
          uri: http://localhost:80
          predicates:
            - Path=/consumer/payment/hystrix/okTest

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway1000
    prefer-ip-address: true