server:
  port: 1000

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order80_route1
          uri: http://localhost:80
          predicates:
            - Path=/consumer/payment/hystrix/okTest
        - id: order80_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway1000
    prefer-ip-address: true