server:
  port: 83

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.116.129:8848

service-url:
  nacos-provider-payment: http://nacos-provider-payment